# Generated by Django 2.1.7 on 2019-02-13 16:32

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(default='', max_length=250, unique=True)),
                ('c_type', models.CharField(choices=[('memory', 'memory'), ('disk', 'disk'), ('network', 'network'), ('log', 'log')], default='memory', max_length=250)),
                ('c_date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('c_status', models.BooleanField(default=False)),
                ('c_file', models.FileField(upload_to='uploads/')),
                ('c_fingerprint', models.CharField(default='', max_length=250)),
                ('c_owner', models.ForeignKey(on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
