# Generated by Django 2.1.7 on 2019-03-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_case_c_supported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='c_supported',
        ),
    ]
