# Generated by Django 2.1.7 on 2019-03-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_remove_case_c_supported'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='c_supported',
            field=models.BooleanField(default=False),
        ),
    ]
