# Generated by Django 2.1.7 on 2019-03-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20190305_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='c_type',
            field=models.CharField(choices=[('memory', 'memory'), ('disk', 'disk'), ('network', 'network')], default='memory', max_length=250),
        ),
    ]
