# Generated by Django 2.1.7 on 2019-03-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20190305_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='c_fingerprint',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
