# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-02 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='date_created',
            new_name='c_date_created',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='file',
            new_name='c_file',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='id',
            new_name='c_id',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='name',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='owner',
            new_name='c_owner',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='status',
            new_name='c_status',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='type',
            new_name='c_type',
        ),
    ]
