# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-02 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20190202_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='c_status',
            field=models.BooleanField(default=True),
        ),
    ]
