# Generated by Django 2.1.7 on 2019-02-12 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20190204_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='c_file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='case',
            name='c_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='c_owner',
            field=models.ForeignKey(on_delete='', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='c_type',
            field=models.CharField(choices=[('memory', 'memory'), ('disk', 'disk'), ('network', 'network'), ('log', 'log')], default='memory', max_length=250),
        ),
    ]
