# Generated by Django 2.1.7 on 2019-02-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20190212_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='c_fingerprint',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='case',
            name='c_name',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
