# Generated by Django 2.1.7 on 2019-02-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_auto_20190212_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='c_id',
            new_name='_id',
        ),
    ]
