# Generated by Django 2.1.7 on 2019-02-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_auto_20190212_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='c_id',
        ),
    ]
