# Generated by Django 2.1.7 on 2019-02-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_remove_case_c_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='c_id',
            field=models.IntegerField(default=0),
        ),
    ]
