# Generated by Django 2.1.7 on 2019-02-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_case_c_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='c_id',
        ),
    ]
